### ISSUE TITLE
INVALID_ARGUMENT: Unrecognized name: IS_GENERATED [at 60:11]

### ISSUE THREAD

**Issue by jpennell** [cloudspannerecosystem/liquibase-spanner#84]
I'm trying a simple example against the spanner emulator and running into an issue.

**changelog.yaml**
```yaml
databaseChangeLog:

  - preConditions:
      onFail: HALT
      onError: HALT

  - includeAll:
      path: ./migrations/
      relativeToChangelogFile: true
```

**migrations/0001_Create_Foo.yaml**
```yaml
databaseChangeLog:

  - preConditions:
      onFail: HALT
      onError: HALT

  - changeSet:
      id: 0001_Create_Foo
      author: jpennell
      changes:
        createTable:
          remarks: Foo
          tableName: Foo
          columns:
            - column:
                remarks: Primary Key
                name: fooId
                type: STRING(255)
                constraints:
                  primaryKey: true
```

and then I run 

```bash 
docker run -it --rm \
  --network=scripts_default \
  -v $(pwd)/liquibase/changelog:/liquibase/changelog \
  -v $(pwd)/liquibase/lib/liquibase-spanner-1.0.2-all.jar:/liquibase/lib/liquibase-spanner-1.0.2-all.jar \
  -e SPANNER_EMULATOR_HOST=spanner:9010 \
  liquibase/liquibase:4.2.0 \
  --defaultsFile=/liquibase/changelog/liquibase.properties \
  update
```

This works totally fine the first time:
```bash
gcloud spanner databases execute-sql database-local --instance instance-dev --sql="SELECT * FROM information_schema.tables;"                                                                                                                                                         git:(master|…1 

TABLE_NAME               PARENT_TABLE_NAME  ON_DELETE_ACTION  SPANNER_STATE
DATABASECHANGELOG        None               None              COMMITTED
DATABASECHANGELOGLOCK    None               None              COMMITTED
Foo                      None               None              COMMITTED
...
```

```bash
gcloud spanner databases execute-sql database-local --instance instance-dev --sql="SELECT * FROM DATABASECHANGELOG ORDER BY orderExecuted ASC;"

id               author    filename                           dateExecuted                 orderExecuted  execType  md5sum                              description                                 comments  tag   liquibase  contexts  labels  deployment_id
0001_Create_Foo  jpennell  ./migrations/0001_Create_Foo.yaml  2021-04-07T13:48:08.008391Z  1              EXECUTED  8:3f443fe17b1689c1129acab7faa1086b  createTable tableName=Foo                             None  4.2.0      None      None    7803287929
```

However; if I run update a second time, I get the following exception:

```
Liquibase Community 4.2.0 by Datical
####################################################
##   _     _             _ _                      ##
##  | |   (_)           (_) |                     ##
##  | |    _  __ _ _   _ _| |__   __ _ ___  ___   ##
##  | |   | |/ _` | | | | | '_ \ / _` / __|/ _ \  ##
##  | |___| | (_| | |_| | | |_) | (_| \__ \  __/  ##
##  \_____/_|\__, |\__,_|_|_.__/ \__,_|___/\___|  ##
##              | |                               ##
##              |_|                               ##
##                                                ## 
##  Get documentation at docs.liquibase.com       ##
##  Get certified courses at learn.liquibase.com  ## 
##  Get advanced features and support at          ##
##      liquibase.com/support                     ##
##                                                ##
####################################################
Starting Liquibase at 14:01:58 (version 4.2.0 #18 built at 2020-11-13 16:49+0000)
Unexpected error running Liquibase: liquibase.exception.DatabaseException: com.google.cloud.spanner.jdbc.JdbcSqlExceptionFactory$JdbcSqlExceptionImpl: INVALID_ARGUMENT: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Unrecognized name: IS_GENERATED [at 60:11]
    WHEN (IS_GENERATED = 'NEVER') THEN 'NO'
          ^ - Statement: 'SELECT TABLE_CATALOG AS TABLE_CAT, TABLE_SCHEMA AS TABLE_SCHEM, TABLE_NAME, COLUMN_NAME,
  CASE
    WHEN SPANNER_TYPE LIKE 'ARRAY%' THEN 2003
    WHEN SPANNER_TYPE = 'BOOL' THEN 16
    WHEN SPANNER_TYPE LIKE 'BYTES%' THEN -2
    WHEN SPANNER_TYPE = 'DATE' THEN 91
    WHEN SPANNER_TYPE = 'FLOAT64' THEN 8
    WHEN SPANNER_TYPE = 'INT64' THEN -5
    WHEN SPANNER_TYPE = 'NUMERIC' THEN 2
    WHEN SPANNER_TYPE LIKE 'STRING%' THEN -9
    WHEN SPANNER_TYPE = 'TIMESTAMP' THEN 93
  END AS DATA_TYPE,
  SPANNER_TYPE AS TYPE_NAME,
  CASE
    WHEN STRPOS(SPANNER_TYPE, '(')=0 THEN
      CASE
        WHEN SPANNER_TYPE = 'INT64' OR SPANNER_TYPE = 'ARRAY<INT64>' THEN 19
        WHEN SPANNER_TYPE = 'NUMERIC' OR SPANNER_TYPE = 'ARRAY<NUMERIC>' THEN 15
        WHEN SPANNER_TYPE = 'FLOAT64' OR SPANNER_TYPE = 'ARRAY<FLOAT64>' THEN 15
        WHEN SPANNER_TYPE = 'BOOL' OR SPANNER_TYPE = 'ARRAY<BOOL>' THEN NULL
        WHEN SPANNER_TYPE = 'DATE' OR SPANNER_TYPE = 'ARRAY<DATE>' THEN 10
        WHEN SPANNER_TYPE = 'TIMESTAMP' OR SPANNER_TYPE = 'ARRAY<TIMESTAMP>' THEN 35
        ELSE 0
      END
    ELSE CAST(REPLACE(SUBSTR(SPANNER_TYPE, STRPOS(SPANNER_TYPE, '(')+1, STRPOS(SPANNER_TYPE, ')')-STRPOS(SPANNER_TYPE, '(')-1), 'MAX', CASE WHEN UPPER(SPANNER_TYPE) LIKE '%STRING%' THEN '2621440' ELSE '10485760' END) AS INT64)
  END AS COLUMN_SIZE,
  0 AS BUFFER_LENGTH,
  CASE
    WHEN SPANNER_TYPE LIKE '%FLOAT64%' THEN 16
    ELSE NULL
  END AS DECIMAL_DIGITS,
  CASE
    WHEN SPANNER_TYPE LIKE '%INT64%' THEN 10
    WHEN SPANNER_TYPE LIKE '%NUMERIC%' THEN 10
    WHEN SPANNER_TYPE LIKE '%FLOAT64%' THEN 2
    ELSE NULL
  END AS NUM_PREC_RADIX,
  CASE
    WHEN IS_NULLABLE = 'YES' THEN 1
    WHEN IS_NULLABLE = 'NO' THEN 0
    ELSE 2
  END AS NULLABLE,
  NULL AS REMARKS,
  NULL AS COLUMN_DEF,
  0 AS SQL_DATA_TYPE,
  0 AS SQL_DATETIME_SUB,
  CASE
    WHEN (SPANNER_TYPE LIKE 'STRING%' OR SPANNER_TYPE LIKE 'ARRAY<STRING%') THEN
      cast(replace(substr(spanner_type, strpos(spanner_type, '(')+1, strpos(spanner_type,')')-strpos(spanner_type, '(')-1), 'MAX', '2621440') as INT64)
    ELSE NULL
  END AS CHAR_OCTET_LENGTH,
  ORDINAL_POSITION,
  IS_NULLABLE,
  NULL AS SCOPE_CATALOG,
  NULL AS SCOPE_SCHEMA,
  NULL AS SCOPE_TABLE,
  NULL AS SOURCE_DATA_TYPE,
  'NO' AS IS_AUTOINCREMENT,
  CASE
    WHEN (IS_GENERATED = 'NEVER') THEN 'NO'
    ELSE 'YES'
  END AS IS_GENERATEDCOLUMN
FROM INFORMATION_SCHEMA.COLUMNS C
WHERE UPPER(C.TABLE_CATALOG) LIKE @p1
  AND UPPER(C.TABLE_SCHEMA) LIKE @p2
  AND UPPER(C.TABLE_NAME) LIKE @p3
  AND UPPER(C.COLUMN_NAME) LIKE @p4
ORDER BY TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, ORDINAL_POSITION'
For more information, please use the --logLevel flag
```

**Comment by olavloite** [comment]
@jpennell What version of the Spanner Emulator are you running?

I just tried the SQL statement from the error on the most recent version of the emulator on both an empty database and one that contains a couple of tables, and it worked in both cases.

**Comment by jpennell** [comment]
@olavloite I'm running the "latest" tag of the spanner emulator from a docker-compose file like

```yaml
  spanner:
    image: gcr.io/cloud-spanner-emulator/emulator
    ports:
        - "9010:9010"
        - "9020:9020"
```

looks like that is version `1.2.0` according to the tag listed in [this image repository](https://console.cloud.google.com/gcr/images/cloud-spanner-emulator/GLOBAL/emulator?gcrImageListsize=30)

**Comment by jpennell** [comment]
@olavloite looks like docker-compose was using an older version, if I reference `1.2.0` specifically

```yaml
  spanner:
    image: gcr.io/cloud-spanner-emulator/emulator:1.2.0
    ports:
        - "9010:9010"
        - "9020:9020"
```

it seemed to download new layers, and the command now works (even after running it multiple times).

Thanks!
